### ISSUE TITLE
Setup to run on a schedule

### ISSUE THREAD

**Issue by jonmclean** [atsid/gcal-leave-scraper#2]
Setup to run on a schedule

**Comment by davija** [comment]
The original plan was to setup to run as a scheduled service.  However after a little bit of research, it appears that google has a push feature that allows it to update a specified service on-change.  So, we will register a "callback" url with google on startup to respond to changes.  Additionally, on startup it will trigger an initial pull to grab events that are not in the database.

**Comment by bleegard** [comment]
No longer needed
