### ISSUE TITLE
Sync users from Google accounts to the Mongo DB

### ISSUE THREAD

**Issue by jonmclean** [atsid/gcal-leave-scraper#3]
Currently the user list is stored in MongoDB.  We need to pull the list of users from Google Apps and sync it with the Mongo DB.

**Comment by jonmclean** [comment]
Google Contacts API does not seem to be available through NodeJS.  See the "Supported APIs" link here: https://github.com/google/google-api-nodejs-client/

**Comment by davija** [comment]
This is by-design.  Getting user accounts from google requires an admin account for the directory.  We don't want the calendar to do this.  It is intended that another application, or the onboarding process will feed the mongo instance.
